// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group.proto

package groupclient

import (
	"context"

	"easy-chat/apps/group/rpc/group"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchIsInGroupReq     = group.BatchIsInGroupReq
	BatchIsInGroupResp    = group.BatchIsInGroupResp
	CreateGroupReq        = group.CreateGroupReq
	CreateGroupResp       = group.CreateGroupResp
	DismissGroupReq       = group.DismissGroupReq
	DismissGroupResp      = group.DismissGroupResp
	GetGroupInfoReq       = group.GetGroupInfoReq
	GetGroupInfoResp      = group.GetGroupInfoResp
	GetGroupMemberIdsReq  = group.GetGroupMemberIdsReq
	GetGroupMemberIdsResp = group.GetGroupMemberIdsResp
	GetGroupMembersReq    = group.GetGroupMembersReq
	GetGroupMembersResp   = group.GetGroupMembersResp
	GetGroupsInfoReq      = group.GetGroupsInfoReq
	GetGroupsInfoResp     = group.GetGroupsInfoResp
	GetUserGroupsReq      = group.GetUserGroupsReq
	GetUserGroupsResp     = group.GetUserGroupsResp
	GroupInfo             = group.GroupInfo
	IsInGroupReq          = group.IsInGroupReq
	IsInGroupResp         = group.IsInGroupResp
	JoinGroupReq          = group.JoinGroupReq
	JoinGroupResp         = group.JoinGroupResp
	KickMemberReq         = group.KickMemberReq
	KickMemberResp        = group.KickMemberResp
	LeaveGroupReq         = group.LeaveGroupReq
	LeaveGroupResp        = group.LeaveGroupResp
	Member                = group.Member
	MuteMemberReq         = group.MuteMemberReq
	MuteMemberResp        = group.MuteMemberResp
	PageInfo              = group.PageInfo
	SetAdminReq           = group.SetAdminReq
	SetAdminResp          = group.SetAdminResp
	TransferOwnerReq      = group.TransferOwnerReq
	TransferOwnerResp     = group.TransferOwnerResp
	UpdateGroupInfoReq    = group.UpdateGroupInfoReq
	UpdateGroupInfoResp   = group.UpdateGroupInfoResp

	Group interface {
		// 基础功能
		CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
		JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*JoinGroupResp, error)
		LeaveGroup(ctx context.Context, in *LeaveGroupReq, opts ...grpc.CallOption) (*LeaveGroupResp, error)
		DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...grpc.CallOption) (*DismissGroupResp, error)
		// 成员管理
		KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error)
		SetAdmin(ctx context.Context, in *SetAdminReq, opts ...grpc.CallOption) (*SetAdminResp, error)
		TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error)
		MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error)
		// 信息查询
		GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
		GetGroupsInfo(ctx context.Context, in *GetGroupsInfoReq, opts ...grpc.CallOption) (*GetGroupsInfoResp, error)
		GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error)
		GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error)
		// 群信息修改
		UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoReq, opts ...grpc.CallOption) (*UpdateGroupInfoResp, error)
		// 辅助功能（供其他RPC服务调用）
		IsInGroup(ctx context.Context, in *IsInGroupReq, opts ...grpc.CallOption) (*IsInGroupResp, error)
		BatchIsInGroup(ctx context.Context, in *BatchIsInGroupReq, opts ...grpc.CallOption) (*BatchIsInGroupResp, error)
		GetGroupMemberIds(ctx context.Context, in *GetGroupMemberIdsReq, opts ...grpc.CallOption) (*GetGroupMemberIdsResp, error)
	}

	defaultGroup struct {
		cli zrpc.Client
	}
)

func NewGroup(cli zrpc.Client) Group {
	return &defaultGroup{
		cli: cli,
	}
}

// 基础功能
func (m *defaultGroup) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

func (m *defaultGroup) JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*JoinGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.JoinGroup(ctx, in, opts...)
}

func (m *defaultGroup) LeaveGroup(ctx context.Context, in *LeaveGroupReq, opts ...grpc.CallOption) (*LeaveGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.LeaveGroup(ctx, in, opts...)
}

func (m *defaultGroup) DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...grpc.CallOption) (*DismissGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.DismissGroup(ctx, in, opts...)
}

// 成员管理
func (m *defaultGroup) KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.KickMember(ctx, in, opts...)
}

func (m *defaultGroup) SetAdmin(ctx context.Context, in *SetAdminReq, opts ...grpc.CallOption) (*SetAdminResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.SetAdmin(ctx, in, opts...)
}

func (m *defaultGroup) TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.TransferOwner(ctx, in, opts...)
}

func (m *defaultGroup) MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.MuteMember(ctx, in, opts...)
}

// 信息查询
func (m *defaultGroup) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetGroupInfo(ctx, in, opts...)
}

func (m *defaultGroup) GetGroupsInfo(ctx context.Context, in *GetGroupsInfoReq, opts ...grpc.CallOption) (*GetGroupsInfoResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetGroupsInfo(ctx, in, opts...)
}

func (m *defaultGroup) GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetGroupMembers(ctx, in, opts...)
}

func (m *defaultGroup) GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetUserGroups(ctx, in, opts...)
}

// 群信息修改
func (m *defaultGroup) UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoReq, opts ...grpc.CallOption) (*UpdateGroupInfoResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.UpdateGroupInfo(ctx, in, opts...)
}

// 辅助功能（供其他RPC服务调用）
func (m *defaultGroup) IsInGroup(ctx context.Context, in *IsInGroupReq, opts ...grpc.CallOption) (*IsInGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.IsInGroup(ctx, in, opts...)
}

func (m *defaultGroup) BatchIsInGroup(ctx context.Context, in *BatchIsInGroupReq, opts ...grpc.CallOption) (*BatchIsInGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.BatchIsInGroup(ctx, in, opts...)
}

func (m *defaultGroup) GetGroupMemberIds(ctx context.Context, in *GetGroupMemberIdsReq, opts ...grpc.CallOption) (*GetGroupMemberIdsResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetGroupMemberIds(ctx, in, opts...)
}
