// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group.proto

package server

import (
	"context"

	"easy-chat/apps/group/rpc/group"
	"easy-chat/apps/group/rpc/internal/logic"
	"easy-chat/apps/group/rpc/internal/svc"
)

type GroupServer struct {
	svcCtx *svc.ServiceContext
	group.UnimplementedGroupServer
}

func NewGroupServer(svcCtx *svc.ServiceContext) *GroupServer {
	return &GroupServer{
		svcCtx: svcCtx,
	}
}

// 基础功能
func (s *GroupServer) CreateGroup(ctx context.Context, in *group.CreateGroupReq) (*group.CreateGroupResp, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *GroupServer) JoinGroup(ctx context.Context, in *group.JoinGroupReq) (*group.JoinGroupResp, error) {
	l := logic.NewJoinGroupLogic(ctx, s.svcCtx)
	return l.JoinGroup(in)
}

func (s *GroupServer) LeaveGroup(ctx context.Context, in *group.LeaveGroupReq) (*group.LeaveGroupResp, error) {
	l := logic.NewLeaveGroupLogic(ctx, s.svcCtx)
	return l.LeaveGroup(in)
}

func (s *GroupServer) DismissGroup(ctx context.Context, in *group.DismissGroupReq) (*group.DismissGroupResp, error) {
	l := logic.NewDismissGroupLogic(ctx, s.svcCtx)
	return l.DismissGroup(in)
}

// 成员管理
func (s *GroupServer) KickMember(ctx context.Context, in *group.KickMemberReq) (*group.KickMemberResp, error) {
	l := logic.NewKickMemberLogic(ctx, s.svcCtx)
	return l.KickMember(in)
}

func (s *GroupServer) SetAdmin(ctx context.Context, in *group.SetAdminReq) (*group.SetAdminResp, error) {
	l := logic.NewSetAdminLogic(ctx, s.svcCtx)
	return l.SetAdmin(in)
}

func (s *GroupServer) TransferOwner(ctx context.Context, in *group.TransferOwnerReq) (*group.TransferOwnerResp, error) {
	l := logic.NewTransferOwnerLogic(ctx, s.svcCtx)
	return l.TransferOwner(in)
}

func (s *GroupServer) MuteMember(ctx context.Context, in *group.MuteMemberReq) (*group.MuteMemberResp, error) {
	l := logic.NewMuteMemberLogic(ctx, s.svcCtx)
	return l.MuteMember(in)
}

// 信息查询
func (s *GroupServer) GetGroupInfo(ctx context.Context, in *group.GetGroupInfoReq) (*group.GetGroupInfoResp, error) {
	l := logic.NewGetGroupInfoLogic(ctx, s.svcCtx)
	return l.GetGroupInfo(in)
}

func (s *GroupServer) GetGroupsInfo(ctx context.Context, in *group.GetGroupsInfoReq) (*group.GetGroupsInfoResp, error) {
	l := logic.NewGetGroupsInfoLogic(ctx, s.svcCtx)
	return l.GetGroupsInfo(in)
}

func (s *GroupServer) GetGroupMembers(ctx context.Context, in *group.GetGroupMembersReq) (*group.GetGroupMembersResp, error) {
	l := logic.NewGetGroupMembersLogic(ctx, s.svcCtx)
	return l.GetGroupMembers(in)
}

func (s *GroupServer) GetUserGroups(ctx context.Context, in *group.GetUserGroupsReq) (*group.GetUserGroupsResp, error) {
	l := logic.NewGetUserGroupsLogic(ctx, s.svcCtx)
	return l.GetUserGroups(in)
}

// 群信息修改
func (s *GroupServer) UpdateGroupInfo(ctx context.Context, in *group.UpdateGroupInfoReq) (*group.UpdateGroupInfoResp, error) {
	l := logic.NewUpdateGroupInfoLogic(ctx, s.svcCtx)
	return l.UpdateGroupInfo(in)
}

// 辅助功能（供其他RPC服务调用）
func (s *GroupServer) IsInGroup(ctx context.Context, in *group.IsInGroupReq) (*group.IsInGroupResp, error) {
	l := logic.NewIsInGroupLogic(ctx, s.svcCtx)
	return l.IsInGroup(in)
}

func (s *GroupServer) BatchIsInGroup(ctx context.Context, in *group.BatchIsInGroupReq) (*group.BatchIsInGroupResp, error) {
	l := logic.NewBatchIsInGroupLogic(ctx, s.svcCtx)
	return l.BatchIsInGroup(in)
}

func (s *GroupServer) GetGroupMemberIds(ctx context.Context, in *group.GetGroupMemberIdsReq) (*group.GetGroupMemberIdsResp, error) {
	l := logic.NewGetGroupMemberIdsLogic(ctx, s.svcCtx)
	return l.GetGroupMemberIds(in)
}
