// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupsFieldNames          = builder.RawFieldNames(&Groups{})
	groupsRows                = strings.Join(groupsFieldNames, ",")
	groupsRowsExpectAutoSet   = strings.Join(stringx.Remove(groupsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	groupsRowsWithPlaceHolder = strings.Join(stringx.Remove(groupsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGroupsIdPrefix      = "cache:groups:id:"
	cacheGroupsGroupIdPrefix = "cache:groups:groupId:"
)

type (
	groupsModel interface {
		Insert(ctx context.Context, data *Groups) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Groups, error)
		FindOneByGroupId(ctx context.Context, groupId uint64) (*Groups, error)
		Update(ctx context.Context, data *Groups) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGroupsModel struct {
		sqlc.CachedConn
		table string
	}

	Groups struct {
		Id            uint64         `db:"id"`
		GroupId       uint64         `db:"group_id"`       // 群ID(业务主键)
		Name          string         `db:"name"`           // 群名称
		OwnerUid      int64          `db:"owner_uid"`      // 群主ID
		Type          int64          `db:"type"`           // 群类型:1-普通群,2-超大群
		Avatar        string         `db:"avatar"`         // 群头像
		Status        int64          `db:"status"`         // 状态:0-已解散,1-正常,2-已封禁
		Description   string         `db:"description"`    // 群简介
		Notice        sql.NullString `db:"notice"`         // 群公告
		MaxMembers    int64          `db:"max_members"`    // 最大成员数
		MemberCount   int64          `db:"member_count"`   // 当前成员数
		JoinType      int64          `db:"join_type"`      // 加群方式:1-自由,2-需审批,3-禁止
		InviteConfirm int64          `db:"invite_confirm"` // 邀请确认:0-否,1-是
		MuteAll       int64          `db:"mute_all"`       // 全员禁言:0-否,1-是
		CreateTime    int64          `db:"create_time"`    // 创建时间
		UpdateTime    int64          `db:"update_time"`    // 更新时间
		DeletedAt     int64          `db:"deleted_at"`     // 删除时间
	}
)

func newGroupsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGroupsModel {
	return &defaultGroupsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`groups`",
	}
}

func (m *defaultGroupsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	groupsGroupIdKey := fmt.Sprintf("%s%v", cacheGroupsGroupIdPrefix, data.GroupId)
	groupsIdKey := fmt.Sprintf("%s%v", cacheGroupsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, groupsGroupIdKey, groupsIdKey)
	return err
}

func (m *defaultGroupsModel) FindOne(ctx context.Context, id uint64) (*Groups, error) {
	groupsIdKey := fmt.Sprintf("%s%v", cacheGroupsIdPrefix, id)
	var resp Groups
	err := m.QueryRowCtx(ctx, &resp, groupsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) FindOneByGroupId(ctx context.Context, groupId uint64) (*Groups, error) {
	groupsGroupIdKey := fmt.Sprintf("%s%v", cacheGroupsGroupIdPrefix, groupId)
	var resp Groups
	err := m.QueryRowIndexCtx(ctx, &resp, groupsGroupIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `group_id` = ? limit 1", groupsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, groupId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) Insert(ctx context.Context, data *Groups) (sql.Result, error) {
	groupsGroupIdKey := fmt.Sprintf("%s%v", cacheGroupsGroupIdPrefix, data.GroupId)
	groupsIdKey := fmt.Sprintf("%s%v", cacheGroupsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, groupsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.Name, data.OwnerUid, data.Type, data.Avatar, data.Status, data.Description, data.Notice, data.MaxMembers, data.MemberCount, data.JoinType, data.InviteConfirm, data.MuteAll, data.DeletedAt)
	}, groupsGroupIdKey, groupsIdKey)
	return ret, err
}

func (m *defaultGroupsModel) Update(ctx context.Context, newData *Groups) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	groupsGroupIdKey := fmt.Sprintf("%s%v", cacheGroupsGroupIdPrefix, data.GroupId)
	groupsIdKey := fmt.Sprintf("%s%v", cacheGroupsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GroupId, newData.Name, newData.OwnerUid, newData.Type, newData.Avatar, newData.Status, newData.Description, newData.Notice, newData.MaxMembers, newData.MemberCount, newData.JoinType, newData.InviteConfirm, newData.MuteAll, newData.DeletedAt, newData.Id)
	}, groupsGroupIdKey, groupsIdKey)
	return err
}

func (m *defaultGroupsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGroupsIdPrefix, primary)
}

func (m *defaultGroupsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGroupsModel) tableName() string {
	return m.table
}
