// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: apps/group/rpc/group.proto

package group

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 群成员信息
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户ID
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`                                    // 角色: 1-普通成员, 2-管理员, 3-群主
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                // 状态: 0-已退出, 1-正常, 2-已被踢, 3-已禁言
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`                             // 群内昵称
	JoinTime      int64                  `protobuf:"varint,5,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`            // 加入时间
	MuteEndTime   int64                  `protobuf:"varint,6,opt,name=mute_end_time,json=muteEndTime,proto3" json:"mute_end_time,omitempty"` // 禁言结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Member) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *Member) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Member) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Member) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

func (x *Member) GetMuteEndTime() int64 {
	if x != nil {
		return x.MuteEndTime
	}
	return 0
}

// 群组信息
type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerUid      int64                  `protobuf:"varint,3,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"` // 1-普通群, 2-超大群
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"` // 0-已解散, 1-正常, 2-已封禁
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Notice        string                 `protobuf:"bytes,8,opt,name=notice,proto3" json:"notice,omitempty"` // 群公告
	MaxMembers    int32                  `protobuf:"varint,9,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`
	MemberCount   int32                  `protobuf:"varint,10,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	JoinType      int32                  `protobuf:"varint,11,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"` // 1-自由加入, 2-需审批, 3-禁止
	MuteAll       int32                  `protobuf:"varint,12,opt,name=mute_all,json=muteAll,proto3" json:"mute_all,omitempty"`    // 0-否, 1-全员禁言
	CreateTime    int64                  `protobuf:"varint,13,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,14,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupInfo) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetOwnerUid() int64 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

func (x *GroupInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GroupInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GroupInfo) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *GroupInfo) GetMaxMembers() int32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *GroupInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GroupInfo) GetJoinType() int32 {
	if x != nil {
		return x.JoinType
	}
	return 0
}

func (x *GroupInfo) GetMuteAll() int32 {
	if x != nil {
		return x.MuteAll
	}
	return 0
}

func (x *GroupInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GroupInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 分页参数
type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量（默认20）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{2}
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ==================== 创建群 ====================
type CreateGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUid      int64                  `protobuf:"varint,1,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`           // 群主ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                    // 群名称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                // 群头像
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                      // 群简介
	MemberIds     []int64                `protobuf:"varint,5,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"` // 初始成员ID列表（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupReq) GetOwnerUid() int64 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

func (x *CreateGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateGroupReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupReq) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupInfo     *GroupInfo             `protobuf:"bytes,2,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"` // 返回完整群信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResp) Reset() {
	*x = CreateGroupResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResp) ProtoMessage() {}

func (x *CreateGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResp.ProtoReflect.Descriptor instead.
func (*CreateGroupResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGroupResp) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupResp) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

// ==================== 加入群 ====================
type JoinGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InviterUid    int64                  `protobuf:"varint,3,opt,name=inviter_uid,json=inviterUid,proto3" json:"inviter_uid,omitempty"` // 邀请人ID（0表示主动加入）
	ApplyMsg      string                 `protobuf:"bytes,4,opt,name=apply_msg,json=applyMsg,proto3" json:"apply_msg,omitempty"`        // 申请消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupReq) Reset() {
	*x = JoinGroupReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupReq) ProtoMessage() {}

func (x *JoinGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupReq.ProtoReflect.Descriptor instead.
func (*JoinGroupReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{5}
}

func (x *JoinGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *JoinGroupReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *JoinGroupReq) GetInviterUid() int64 {
	if x != nil {
		return x.InviterUid
	}
	return 0
}

func (x *JoinGroupReq) GetApplyMsg() string {
	if x != nil {
		return x.ApplyMsg
	}
	return ""
}

type JoinGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedApproval  bool                   `protobuf:"varint,1,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"` // 是否需要审批
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupResp) Reset() {
	*x = JoinGroupResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResp) ProtoMessage() {}

func (x *JoinGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResp.ProtoReflect.Descriptor instead.
func (*JoinGroupResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{6}
}

func (x *JoinGroupResp) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

// ==================== 退出群 ====================
type LeaveGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupReq) Reset() {
	*x = LeaveGroupReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupReq) ProtoMessage() {}

func (x *LeaveGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupReq.ProtoReflect.Descriptor instead.
func (*LeaveGroupReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *LeaveGroupReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LeaveGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupResp) Reset() {
	*x = LeaveGroupResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupResp) ProtoMessage() {}

func (x *LeaveGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupResp.ProtoReflect.Descriptor instead.
func (*LeaveGroupResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{8}
}

// ==================== 解散群 ====================
type DismissGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   int64                  `protobuf:"varint,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"` // 操作者ID（必须是群主）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupReq) Reset() {
	*x = DismissGroupReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupReq) ProtoMessage() {}

func (x *DismissGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupReq.ProtoReflect.Descriptor instead.
func (*DismissGroupReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{9}
}

func (x *DismissGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DismissGroupReq) GetOperatorUid() int64 {
	if x != nil {
		return x.OperatorUid
	}
	return 0
}

type DismissGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupResp) Reset() {
	*x = DismissGroupResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupResp) ProtoMessage() {}

func (x *DismissGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupResp.ProtoReflect.Descriptor instead.
func (*DismissGroupResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{10}
}

// ==================== 踢出成员 ====================
type KickMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   int64                  `protobuf:"varint,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"` // 操作者ID（群主或管理员）
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 被踢出的用户ID
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                               // 踢出原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMemberReq) Reset() {
	*x = KickMemberReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMemberReq) ProtoMessage() {}

func (x *KickMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMemberReq.ProtoReflect.Descriptor instead.
func (*KickMemberReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{11}
}

func (x *KickMemberReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *KickMemberReq) GetOperatorUid() int64 {
	if x != nil {
		return x.OperatorUid
	}
	return 0
}

func (x *KickMemberReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KickMemberReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type KickMemberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMemberResp) Reset() {
	*x = KickMemberResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMemberResp) ProtoMessage() {}

func (x *KickMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMemberResp.ProtoReflect.Descriptor instead.
func (*KickMemberResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{12}
}

// ==================== 设置管理员 ====================
type SetAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   int64                  `protobuf:"varint,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"` // 操作者ID（必须是群主）
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 目标用户ID
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`                                  // 角色：1-取消管理员, 2-设为管理员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminReq) Reset() {
	*x = SetAdminReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminReq) ProtoMessage() {}

func (x *SetAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminReq.ProtoReflect.Descriptor instead.
func (*SetAdminReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{13}
}

func (x *SetAdminReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SetAdminReq) GetOperatorUid() int64 {
	if x != nil {
		return x.OperatorUid
	}
	return 0
}

func (x *SetAdminReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetAdminReq) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type SetAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminResp) Reset() {
	*x = SetAdminResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminResp) ProtoMessage() {}

func (x *SetAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminResp.ProtoReflect.Descriptor instead.
func (*SetAdminResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{14}
}

// ==================== 转让群主 ====================
type TransferOwnerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   int64                  `protobuf:"varint,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"`   // 操作者ID（必须是群主）
	NewOwnerUid   int64                  `protobuf:"varint,3,opt,name=new_owner_uid,json=newOwnerUid,proto3" json:"new_owner_uid,omitempty"` // 新群主ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnerReq) Reset() {
	*x = TransferOwnerReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnerReq) ProtoMessage() {}

func (x *TransferOwnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnerReq.ProtoReflect.Descriptor instead.
func (*TransferOwnerReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{15}
}

func (x *TransferOwnerReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *TransferOwnerReq) GetOperatorUid() int64 {
	if x != nil {
		return x.OperatorUid
	}
	return 0
}

func (x *TransferOwnerReq) GetNewOwnerUid() int64 {
	if x != nil {
		return x.NewOwnerUid
	}
	return 0
}

type TransferOwnerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnerResp) Reset() {
	*x = TransferOwnerResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnerResp) ProtoMessage() {}

func (x *TransferOwnerResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnerResp.ProtoReflect.Descriptor instead.
func (*TransferOwnerResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{16}
}

// ==================== 禁言/解除禁言 ====================
type MuteMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   int64                  `protobuf:"varint,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"` // 操作者ID（群主或管理员）
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 被禁言的用户ID
	MuteSeconds   int64                  `protobuf:"varint,4,opt,name=mute_seconds,json=muteSeconds,proto3" json:"mute_seconds,omitempty"` // 禁言时长（秒）, 0表示解除禁言
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberReq) Reset() {
	*x = MuteMemberReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberReq) ProtoMessage() {}

func (x *MuteMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberReq.ProtoReflect.Descriptor instead.
func (*MuteMemberReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{17}
}

func (x *MuteMemberReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MuteMemberReq) GetOperatorUid() int64 {
	if x != nil {
		return x.OperatorUid
	}
	return 0
}

func (x *MuteMemberReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MuteMemberReq) GetMuteSeconds() int64 {
	if x != nil {
		return x.MuteSeconds
	}
	return 0
}

type MuteMemberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberResp) Reset() {
	*x = MuteMemberResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberResp) ProtoMessage() {}

func (x *MuteMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberResp.ProtoReflect.Descriptor instead.
func (*MuteMemberResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{18}
}

// ==================== 获取群成员列表 ====================
type GetGroupMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 状态筛选（0-全部, 1-仅正常成员）
	Page          *PageInfo              `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`      // 分页参数（大群必须分页）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersReq) Reset() {
	*x = GetGroupMembersReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersReq) ProtoMessage() {}

func (x *GetGroupMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersReq.ProtoReflect.Descriptor instead.
func (*GetGroupMembersReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{19}
}

func (x *GetGroupMembersReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupMembersReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetGroupMembersReq) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetGroupMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Member              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersResp) Reset() {
	*x = GetGroupMembersResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersResp) ProtoMessage() {}

func (x *GetGroupMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersResp.ProtoReflect.Descriptor instead.
func (*GetGroupMembersResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{20}
}

func (x *GetGroupMembersResp) GetList() []*Member {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetGroupMembersResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ==================== 获取群信息 ====================
type GetGroupInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoReq) Reset() {
	*x = GetGroupInfoReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoReq) ProtoMessage() {}

func (x *GetGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoReq.ProtoReflect.Descriptor instead.
func (*GetGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{21}
}

func (x *GetGroupInfoReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupInfo     *GroupInfo             `protobuf:"bytes,1,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoResp) Reset() {
	*x = GetGroupInfoResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoResp) ProtoMessage() {}

func (x *GetGroupInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoResp.ProtoReflect.Descriptor instead.
func (*GetGroupInfoResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{22}
}

func (x *GetGroupInfoResp) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

// ==================== 批量获取群信息 ====================
type GetGroupsInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIds      []int64                `protobuf:"varint,1,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"` // 群ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsInfoReq) Reset() {
	*x = GetGroupsInfoReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsInfoReq) ProtoMessage() {}

func (x *GetGroupsInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsInfoReq.ProtoReflect.Descriptor instead.
func (*GetGroupsInfoReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{23}
}

func (x *GetGroupsInfoReq) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

type GetGroupsInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        map[int64]*GroupInfo   `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: group_id, value: GroupInfo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsInfoResp) Reset() {
	*x = GetGroupsInfoResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsInfoResp) ProtoMessage() {}

func (x *GetGroupsInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsInfoResp.ProtoReflect.Descriptor instead.
func (*GetGroupsInfoResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{24}
}

func (x *GetGroupsInfoResp) GetGroups() map[int64]*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

// ==================== 更新群信息 ====================
type UpdateGroupInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   int64                  `protobuf:"varint,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"` // 操作者ID（群主或管理员）
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                   // 群名称（可选）
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`                               // 群头像（可选）
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                     // 群简介（可选）
	Notice        string                 `protobuf:"bytes,6,opt,name=notice,proto3" json:"notice,omitempty"`                               // 群公告（可选）
	JoinType      int32                  `protobuf:"varint,7,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`          // 加群方式（可选）
	MuteAll       int32                  `protobuf:"varint,8,opt,name=mute_all,json=muteAll,proto3" json:"mute_all,omitempty"`             // 全员禁言（可选，-1表示不修改）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupInfoReq) Reset() {
	*x = UpdateGroupInfoReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoReq) ProtoMessage() {}

func (x *UpdateGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateGroupInfoReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetOperatorUid() int64 {
	if x != nil {
		return x.OperatorUid
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetJoinType() int32 {
	if x != nil {
		return x.JoinType
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetMuteAll() int32 {
	if x != nil {
		return x.MuteAll
	}
	return 0
}

type UpdateGroupInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupInfoResp) Reset() {
	*x = UpdateGroupInfoResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoResp) ProtoMessage() {}

func (x *UpdateGroupInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoResp.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{26}
}

// ==================== 获取用户加入的群列表 ====================
type GetUserGroupsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 状态筛选（0-全部, 1-仅正常的群）
	Page          *PageInfo              `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGroupsReq) Reset() {
	*x = GetUserGroupsReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGroupsReq) ProtoMessage() {}

func (x *GetUserGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGroupsReq.ProtoReflect.Descriptor instead.
func (*GetUserGroupsReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserGroupsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserGroupsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetUserGroupsReq) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetUserGroupsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GroupInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGroupsResp) Reset() {
	*x = GetUserGroupsResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGroupsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGroupsResp) ProtoMessage() {}

func (x *GetUserGroupsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGroupsResp.ProtoReflect.Descriptor instead.
func (*GetUserGroupsResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{28}
}

func (x *GetUserGroupsResp) GetList() []*GroupInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserGroupsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ==================== 检查用户是否在群内 ====================
type IsInGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsInGroupReq) Reset() {
	*x = IsInGroupReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsInGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsInGroupReq) ProtoMessage() {}

func (x *IsInGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsInGroupReq.ProtoReflect.Descriptor instead.
func (*IsInGroupReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{29}
}

func (x *IsInGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *IsInGroupReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsInGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"` // 角色（如果在群内）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsInGroupResp) Reset() {
	*x = IsInGroupResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsInGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsInGroupResp) ProtoMessage() {}

func (x *IsInGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsInGroupResp.ProtoReflect.Descriptor instead.
func (*IsInGroupResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{30}
}

func (x *IsInGroupResp) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *IsInGroupResp) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

// ==================== 批量检查用户是否在群内 ====================
type BatchIsInGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIds       []int64                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIsInGroupReq) Reset() {
	*x = BatchIsInGroupReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIsInGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIsInGroupReq) ProtoMessage() {}

func (x *BatchIsInGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIsInGroupReq.ProtoReflect.Descriptor instead.
func (*BatchIsInGroupReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{31}
}

func (x *BatchIsInGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *BatchIsInGroupReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type BatchIsInGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[int64]bool         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key: user_id, value: is_member
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIsInGroupResp) Reset() {
	*x = BatchIsInGroupResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIsInGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIsInGroupResp) ProtoMessage() {}

func (x *BatchIsInGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIsInGroupResp.ProtoReflect.Descriptor instead.
func (*BatchIsInGroupResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{32}
}

func (x *BatchIsInGroupResp) GetResults() map[int64]bool {
	if x != nil {
		return x.Results
	}
	return nil
}

// ==================== 获取群成员ID列表（用于群发消息） ====================
type GetGroupMemberIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 1-仅正常成员, 3-排除禁言成员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberIdsReq) Reset() {
	*x = GetGroupMemberIdsReq{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberIdsReq) ProtoMessage() {}

func (x *GetGroupMemberIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberIdsReq.ProtoReflect.Descriptor instead.
func (*GetGroupMemberIdsReq) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{33}
}

func (x *GetGroupMemberIdsReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupMemberIdsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetGroupMemberIdsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberIdsResp) Reset() {
	*x = GetGroupMemberIdsResp{}
	mi := &file_apps_group_rpc_group_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberIdsResp) ProtoMessage() {}

func (x *GetGroupMemberIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_group_rpc_group_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberIdsResp.ProtoReflect.Descriptor instead.
func (*GetGroupMemberIdsResp) Descriptor() ([]byte, []int) {
	return file_apps_group_rpc_group_proto_rawDescGZIP(), []int{34}
}

func (x *GetGroupMemberIdsResp) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_apps_group_rpc_group_proto protoreflect.FileDescriptor

const file_apps_group_rpc_group_proto_rawDesc = "" +
	"\n" +
	"\x1aapps/group/rpc/group.proto\x12\x05group\"\xaa\x01\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x1b\n" +
	"\tjoin_time\x18\x05 \x01(\x03R\bjoinTime\x12\"\n" +
	"\rmute_end_time\x18\x06 \x01(\x03R\vmuteEndTime\"\x93\x03\n" +
	"\tGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\towner_uid\x18\x03 \x01(\x03R\bownerUid\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06notice\x18\b \x01(\tR\x06notice\x12\x1f\n" +
	"\vmax_members\x18\t \x01(\x05R\n" +
	"maxMembers\x12!\n" +
	"\fmember_count\x18\n" +
	" \x01(\x05R\vmemberCount\x12\x1b\n" +
	"\tjoin_type\x18\v \x01(\x05R\bjoinType\x12\x19\n" +
	"\bmute_all\x18\f \x01(\x05R\amuteAll\x12\x1f\n" +
	"\vcreate_time\x18\r \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x0e \x01(\x03R\n" +
	"updateTime\";\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x9a\x01\n" +
	"\x0eCreateGroupReq\x12\x1b\n" +
	"\towner_uid\x18\x01 \x01(\x03R\bownerUid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x05 \x03(\x03R\tmemberIds\"]\n" +
	"\x0fCreateGroupResp\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12/\n" +
	"\n" +
	"group_info\x18\x02 \x01(\v2\x10.group.GroupInfoR\tgroupInfo\"\x80\x01\n" +
	"\fJoinGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vinviter_uid\x18\x03 \x01(\x03R\n" +
	"inviterUid\x12\x1b\n" +
	"\tapply_msg\x18\x04 \x01(\tR\bapplyMsg\"4\n" +
	"\rJoinGroupResp\x12#\n" +
	"\rneed_approval\x18\x01 \x01(\bR\fneedApproval\"C\n" +
	"\rLeaveGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x10\n" +
	"\x0eLeaveGroupResp\"O\n" +
	"\x0fDismissGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\x03R\voperatorUid\"\x12\n" +
	"\x10DismissGroupResp\"~\n" +
	"\rKickMemberReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\x03R\voperatorUid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x10\n" +
	"\x0eKickMemberResp\"x\n" +
	"\vSetAdminReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\x03R\voperatorUid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\"\x0e\n" +
	"\fSetAdminResp\"t\n" +
	"\x10TransferOwnerReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\x03R\voperatorUid\x12\"\n" +
	"\rnew_owner_uid\x18\x03 \x01(\x03R\vnewOwnerUid\"\x13\n" +
	"\x11TransferOwnerResp\"\x89\x01\n" +
	"\rMuteMemberReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\x03R\voperatorUid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12!\n" +
	"\fmute_seconds\x18\x04 \x01(\x03R\vmuteSeconds\"\x10\n" +
	"\x0eMuteMemberResp\"l\n" +
	"\x12GetGroupMembersReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12#\n" +
	"\x04page\x18\x03 \x01(\v2\x0f.group.PageInfoR\x04page\"N\n" +
	"\x13GetGroupMembersResp\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.group.MemberR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\",\n" +
	"\x0fGetGroupInfoReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"C\n" +
	"\x10GetGroupInfoResp\x12/\n" +
	"\n" +
	"group_info\x18\x01 \x01(\v2\x10.group.GroupInfoR\tgroupInfo\"/\n" +
	"\x10GetGroupsInfoReq\x12\x1b\n" +
	"\tgroup_ids\x18\x01 \x03(\x03R\bgroupIds\"\x9e\x01\n" +
	"\x11GetGroupsInfoResp\x12<\n" +
	"\x06groups\x18\x01 \x03(\v2$.group.GetGroupsInfoResp.GroupsEntryR\x06groups\x1aK\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.group.GroupInfoR\x05value:\x028\x01\"\xf0\x01\n" +
	"\x12UpdateGroupInfoReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\x03R\voperatorUid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06notice\x18\x06 \x01(\tR\x06notice\x12\x1b\n" +
	"\tjoin_type\x18\a \x01(\x05R\bjoinType\x12\x19\n" +
	"\bmute_all\x18\b \x01(\x05R\amuteAll\"\x15\n" +
	"\x13UpdateGroupInfoResp\"h\n" +
	"\x10GetUserGroupsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12#\n" +
	"\x04page\x18\x03 \x01(\v2\x0f.group.PageInfoR\x04page\"O\n" +
	"\x11GetUserGroupsResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.group.GroupInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"B\n" +
	"\fIsInGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"@\n" +
	"\rIsInGroupResp\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\"I\n" +
	"\x11BatchIsInGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x03R\auserIds\"\x92\x01\n" +
	"\x12BatchIsInGroupResp\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.group.BatchIsInGroupResp.ResultsEntryR\aresults\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"I\n" +
	"\x14GetGroupMemberIdsReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"2\n" +
	"\x15GetGroupMemberIdsResp\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds2\x94\b\n" +
	"\x05Group\x12<\n" +
	"\vCreateGroup\x12\x15.group.CreateGroupReq\x1a\x16.group.CreateGroupResp\x126\n" +
	"\tJoinGroup\x12\x13.group.JoinGroupReq\x1a\x14.group.JoinGroupResp\x129\n" +
	"\n" +
	"LeaveGroup\x12\x14.group.LeaveGroupReq\x1a\x15.group.LeaveGroupResp\x12?\n" +
	"\fDismissGroup\x12\x16.group.DismissGroupReq\x1a\x17.group.DismissGroupResp\x129\n" +
	"\n" +
	"KickMember\x12\x14.group.KickMemberReq\x1a\x15.group.KickMemberResp\x123\n" +
	"\bSetAdmin\x12\x12.group.SetAdminReq\x1a\x13.group.SetAdminResp\x12B\n" +
	"\rTransferOwner\x12\x17.group.TransferOwnerReq\x1a\x18.group.TransferOwnerResp\x129\n" +
	"\n" +
	"MuteMember\x12\x14.group.MuteMemberReq\x1a\x15.group.MuteMemberResp\x12?\n" +
	"\fGetGroupInfo\x12\x16.group.GetGroupInfoReq\x1a\x17.group.GetGroupInfoResp\x12B\n" +
	"\rGetGroupsInfo\x12\x17.group.GetGroupsInfoReq\x1a\x18.group.GetGroupsInfoResp\x12H\n" +
	"\x0fGetGroupMembers\x12\x19.group.GetGroupMembersReq\x1a\x1a.group.GetGroupMembersResp\x12B\n" +
	"\rGetUserGroups\x12\x17.group.GetUserGroupsReq\x1a\x18.group.GetUserGroupsResp\x12H\n" +
	"\x0fUpdateGroupInfo\x12\x19.group.UpdateGroupInfoReq\x1a\x1a.group.UpdateGroupInfoResp\x126\n" +
	"\tIsInGroup\x12\x13.group.IsInGroupReq\x1a\x14.group.IsInGroupResp\x12E\n" +
	"\x0eBatchIsInGroup\x12\x18.group.BatchIsInGroupReq\x1a\x19.group.BatchIsInGroupResp\x12N\n" +
	"\x11GetGroupMemberIds\x12\x1b.group.GetGroupMemberIdsReq\x1a\x1c.group.GetGroupMemberIdsRespB\tZ\a./groupb\x06proto3"

var (
	file_apps_group_rpc_group_proto_rawDescOnce sync.Once
	file_apps_group_rpc_group_proto_rawDescData []byte
)

func file_apps_group_rpc_group_proto_rawDescGZIP() []byte {
	file_apps_group_rpc_group_proto_rawDescOnce.Do(func() {
		file_apps_group_rpc_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_group_rpc_group_proto_rawDesc), len(file_apps_group_rpc_group_proto_rawDesc)))
	})
	return file_apps_group_rpc_group_proto_rawDescData
}

var file_apps_group_rpc_group_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_apps_group_rpc_group_proto_goTypes = []any{
	(*Member)(nil),                // 0: group.Member
	(*GroupInfo)(nil),             // 1: group.GroupInfo
	(*PageInfo)(nil),              // 2: group.PageInfo
	(*CreateGroupReq)(nil),        // 3: group.CreateGroupReq
	(*CreateGroupResp)(nil),       // 4: group.CreateGroupResp
	(*JoinGroupReq)(nil),          // 5: group.JoinGroupReq
	(*JoinGroupResp)(nil),         // 6: group.JoinGroupResp
	(*LeaveGroupReq)(nil),         // 7: group.LeaveGroupReq
	(*LeaveGroupResp)(nil),        // 8: group.LeaveGroupResp
	(*DismissGroupReq)(nil),       // 9: group.DismissGroupReq
	(*DismissGroupResp)(nil),      // 10: group.DismissGroupResp
	(*KickMemberReq)(nil),         // 11: group.KickMemberReq
	(*KickMemberResp)(nil),        // 12: group.KickMemberResp
	(*SetAdminReq)(nil),           // 13: group.SetAdminReq
	(*SetAdminResp)(nil),          // 14: group.SetAdminResp
	(*TransferOwnerReq)(nil),      // 15: group.TransferOwnerReq
	(*TransferOwnerResp)(nil),     // 16: group.TransferOwnerResp
	(*MuteMemberReq)(nil),         // 17: group.MuteMemberReq
	(*MuteMemberResp)(nil),        // 18: group.MuteMemberResp
	(*GetGroupMembersReq)(nil),    // 19: group.GetGroupMembersReq
	(*GetGroupMembersResp)(nil),   // 20: group.GetGroupMembersResp
	(*GetGroupInfoReq)(nil),       // 21: group.GetGroupInfoReq
	(*GetGroupInfoResp)(nil),      // 22: group.GetGroupInfoResp
	(*GetGroupsInfoReq)(nil),      // 23: group.GetGroupsInfoReq
	(*GetGroupsInfoResp)(nil),     // 24: group.GetGroupsInfoResp
	(*UpdateGroupInfoReq)(nil),    // 25: group.UpdateGroupInfoReq
	(*UpdateGroupInfoResp)(nil),   // 26: group.UpdateGroupInfoResp
	(*GetUserGroupsReq)(nil),      // 27: group.GetUserGroupsReq
	(*GetUserGroupsResp)(nil),     // 28: group.GetUserGroupsResp
	(*IsInGroupReq)(nil),          // 29: group.IsInGroupReq
	(*IsInGroupResp)(nil),         // 30: group.IsInGroupResp
	(*BatchIsInGroupReq)(nil),     // 31: group.BatchIsInGroupReq
	(*BatchIsInGroupResp)(nil),    // 32: group.BatchIsInGroupResp
	(*GetGroupMemberIdsReq)(nil),  // 33: group.GetGroupMemberIdsReq
	(*GetGroupMemberIdsResp)(nil), // 34: group.GetGroupMemberIdsResp
	nil,                           // 35: group.GetGroupsInfoResp.GroupsEntry
	nil,                           // 36: group.BatchIsInGroupResp.ResultsEntry
}
var file_apps_group_rpc_group_proto_depIdxs = []int32{
	1,  // 0: group.CreateGroupResp.group_info:type_name -> group.GroupInfo
	2,  // 1: group.GetGroupMembersReq.page:type_name -> group.PageInfo
	0,  // 2: group.GetGroupMembersResp.list:type_name -> group.Member
	1,  // 3: group.GetGroupInfoResp.group_info:type_name -> group.GroupInfo
	35, // 4: group.GetGroupsInfoResp.groups:type_name -> group.GetGroupsInfoResp.GroupsEntry
	2,  // 5: group.GetUserGroupsReq.page:type_name -> group.PageInfo
	1,  // 6: group.GetUserGroupsResp.list:type_name -> group.GroupInfo
	36, // 7: group.BatchIsInGroupResp.results:type_name -> group.BatchIsInGroupResp.ResultsEntry
	1,  // 8: group.GetGroupsInfoResp.GroupsEntry.value:type_name -> group.GroupInfo
	3,  // 9: group.Group.CreateGroup:input_type -> group.CreateGroupReq
	5,  // 10: group.Group.JoinGroup:input_type -> group.JoinGroupReq
	7,  // 11: group.Group.LeaveGroup:input_type -> group.LeaveGroupReq
	9,  // 12: group.Group.DismissGroup:input_type -> group.DismissGroupReq
	11, // 13: group.Group.KickMember:input_type -> group.KickMemberReq
	13, // 14: group.Group.SetAdmin:input_type -> group.SetAdminReq
	15, // 15: group.Group.TransferOwner:input_type -> group.TransferOwnerReq
	17, // 16: group.Group.MuteMember:input_type -> group.MuteMemberReq
	21, // 17: group.Group.GetGroupInfo:input_type -> group.GetGroupInfoReq
	23, // 18: group.Group.GetGroupsInfo:input_type -> group.GetGroupsInfoReq
	19, // 19: group.Group.GetGroupMembers:input_type -> group.GetGroupMembersReq
	27, // 20: group.Group.GetUserGroups:input_type -> group.GetUserGroupsReq
	25, // 21: group.Group.UpdateGroupInfo:input_type -> group.UpdateGroupInfoReq
	29, // 22: group.Group.IsInGroup:input_type -> group.IsInGroupReq
	31, // 23: group.Group.BatchIsInGroup:input_type -> group.BatchIsInGroupReq
	33, // 24: group.Group.GetGroupMemberIds:input_type -> group.GetGroupMemberIdsReq
	4,  // 25: group.Group.CreateGroup:output_type -> group.CreateGroupResp
	6,  // 26: group.Group.JoinGroup:output_type -> group.JoinGroupResp
	8,  // 27: group.Group.LeaveGroup:output_type -> group.LeaveGroupResp
	10, // 28: group.Group.DismissGroup:output_type -> group.DismissGroupResp
	12, // 29: group.Group.KickMember:output_type -> group.KickMemberResp
	14, // 30: group.Group.SetAdmin:output_type -> group.SetAdminResp
	16, // 31: group.Group.TransferOwner:output_type -> group.TransferOwnerResp
	18, // 32: group.Group.MuteMember:output_type -> group.MuteMemberResp
	22, // 33: group.Group.GetGroupInfo:output_type -> group.GetGroupInfoResp
	24, // 34: group.Group.GetGroupsInfo:output_type -> group.GetGroupsInfoResp
	20, // 35: group.Group.GetGroupMembers:output_type -> group.GetGroupMembersResp
	28, // 36: group.Group.GetUserGroups:output_type -> group.GetUserGroupsResp
	26, // 37: group.Group.UpdateGroupInfo:output_type -> group.UpdateGroupInfoResp
	30, // 38: group.Group.IsInGroup:output_type -> group.IsInGroupResp
	32, // 39: group.Group.BatchIsInGroup:output_type -> group.BatchIsInGroupResp
	34, // 40: group.Group.GetGroupMemberIds:output_type -> group.GetGroupMemberIdsResp
	25, // [25:41] is the sub-list for method output_type
	9,  // [9:25] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_apps_group_rpc_group_proto_init() }
func file_apps_group_rpc_group_proto_init() {
	if File_apps_group_rpc_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_group_rpc_group_proto_rawDesc), len(file_apps_group_rpc_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_group_rpc_group_proto_goTypes,
		DependencyIndexes: file_apps_group_rpc_group_proto_depIdxs,
		MessageInfos:      file_apps_group_rpc_group_proto_msgTypes,
	}.Build()
	File_apps_group_rpc_group_proto = out.File
	file_apps_group_rpc_group_proto_goTypes = nil
	file_apps_group_rpc_group_proto_depIdxs = nil
}
