// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateGroupReq struct {
	Name        string  `json:"name"`                 // 群名称
	Avatar      string  `json:"avatar,optional"`      // 群头像
	Description string  `json:"description,optional"` // 群简介
	MemberIds   []int64 `json:"member_ids,optional"`  // 初始成员ID列表
}

type CreateGroupResp struct {
	GroupId   int64     `json:"group_id"`
	GroupInfo GroupInfo `json:"group_info"`
}

type DismissGroupReq struct {
	GroupId int64 `json:"group_id"` // 群ID
}

type DismissGroupResp struct {
}

type GetGroupInfoReq struct {
	GroupId int64 `json:"group_id"` // 群ID
}

type GetGroupInfoResp struct {
	GroupInfo GroupInfo `json:"group_info"`
}

type GetGroupMembersReq struct {
	GroupId int64    `json:"group_id"`         // 群ID
	Status  int32    `json:"status,default=1"` // 状态筛选 0-全部,1-仅正常
	Page    PageInfo `json:"page,optional"`    // 分页参数
}

type GetGroupMembersResp struct {
	List  []MemberInfo `json:"list"`  // 成员列表
	Total int32        `json:"total"` // 总数
}

type GetGroupsInfoReq struct {
	GroupIds []int64 `json:"group_ids"` // 群ID列表
}

type GetGroupsInfoResp struct {
	Groups map[string]GroupInfo `json:"groups"` // key: group_id, value: GroupInfo
}

type GetUserGroupsReq struct {
	Status int32    `json:"status,default=1"` // 状态筛选 0-全部,1-仅正常的群
	Page   PageInfo `json:"page,optional"`    // 分页参数
}

type GetUserGroupsResp struct {
	List  []GroupInfo `json:"list"`  // 群列表
	Total int32       `json:"total"` // 总数
}

type GroupInfo struct {
	GroupId     int64  `json:"group_id"`
	Name        string `json:"name"`
	OwnerUid    int64  `json:"owner_uid"`
	Type        int32  `json:"type"` // 1-普通群,2-超大群
	Avatar      string `json:"avatar"`
	Status      int32  `json:"status"` // 0-已解散,1-正常,2-已封禁
	Description string `json:"description"`
	Notice      string `json:"notice"`       // 群公告
	MaxMembers  int32  `json:"max_members"`  // 最大成员数
	MemberCount int32  `json:"member_count"` // 当前成员数
	JoinType    int32  `json:"join_type"`    // 1-自由,2-需审批,3-禁止
	MuteAll     int32  `json:"mute_all"`     // 0-否,1-全员禁言
	CreateTime  int64  `json:"create_time"`
	UpdateTime  int64  `json:"update_time"`
}

type IsInGroupReq struct {
	GroupId int64 `json:"group_id"` // 群ID
	UserId  int64 `json:"user_id"`  // 用户ID
}

type IsInGroupResp struct {
	IsMember bool  `json:"is_member"` // 是否在群内
	Role     int32 `json:"role"`      // 角色（如果在群内）
}

type JoinGroupReq struct {
	GroupId    int64  `json:"group_id"`             // 群ID
	InviterUid int64  `json:"inviter_uid,optional"` // 邀请人ID
	ApplyMsg   string `json:"apply_msg,optional"`   // 申请消息
}

type JoinGroupResp struct {
	NeedApproval bool `json:"need_approval"` // 是否需要审批
}

type KickMemberReq struct {
	GroupId int64  `json:"group_id"`        // 群ID
	UserId  int64  `json:"user_id"`         // 被踢出的用户ID
	Reason  string `json:"reason,optional"` // 踢出原因
}

type KickMemberResp struct {
}

type LeaveGroupReq struct {
	GroupId int64 `json:"group_id"` // 群ID
}

type LeaveGroupResp struct {
}

type MemberInfo struct {
	UserId      int64  `json:"user_id"`
	Role        int32  `json:"role"`          // 1-普通,2-管理员,3-群主
	Status      int32  `json:"status"`        // 0-已退出,1-正常,2-已被踢,3-已禁言
	Nickname    string `json:"nickname"`      // 群内昵称
	JoinTime    int64  `json:"join_time"`     // 加入时间
	MuteEndTime int64  `json:"mute_end_time"` // 禁言结束时间
	GroupId     int64  `json:"group_id"`      // 群ID
}

type MuteMemberReq struct {
	GroupId     int64 `json:"group_id"`     // 群ID
	UserId      int64 `json:"user_id"`      // 被禁言的用户ID
	MuteSeconds int64 `json:"mute_seconds"` // 禁言时长(秒),0表示解除禁言
}

type MuteMemberResp struct {
}

type PageInfo struct {
	Page     int32 `json:"page,default=1"`       // 页码
	PageSize int32 `json:"page_size,default=20"` // 每页数量
}

type SetAdminReq struct {
	GroupId int64 `json:"group_id"` // 群ID
	UserId  int64 `json:"user_id"`  // 目标用户ID
	Role    int32 `json:"role"`     // 角色：1-取消管理员,2-设为管理员
}

type SetAdminResp struct {
}

type TransferOwnerReq struct {
	GroupId     int64 `json:"group_id"`      // 群ID
	NewOwnerUid int64 `json:"new_owner_uid"` // 新群主ID
}

type TransferOwnerResp struct {
}

type UpdateGroupInfoReq struct {
	GroupId     int64  `json:"group_id"`             // 群ID
	Name        string `json:"name,optional"`        // 群名称
	Avatar      string `json:"avatar,optional"`      // 群头像
	Description string `json:"description,optional"` // 群简介
	Notice      string `json:"notice,optional"`      // 群公告
	JoinType    int32  `json:"join_type,optional"`   // 加群方式
	MuteAll     int32  `json:"mute_all,optional"`    // 全员禁言 -1表示不修改
}

type UpdateGroupInfoResp struct {
}
