// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: msg.proto

package msgclient

import (
	"context"

	"easy-chat/apps/msg/rpc/msg"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetHistoryReq  = msg.GetHistoryReq
	GetHistoryResp = msg.GetHistoryResp
	MsgData        = msg.MsgData
	SendMsgReq     = msg.SendMsgReq
	SendMsgResp    = msg.SendMsgResp

	Msg interface {
		// 发送消息：处理存储、生成ID、广播
		SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgResp, error)
		// 获取消息历史
		GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error)
	}

	defaultMsg struct {
		cli zrpc.Client
	}
)

func NewMsg(cli zrpc.Client) Msg {
	return &defaultMsg{
		cli: cli,
	}
}

// 发送消息：处理存储、生成ID、广播
func (m *defaultMsg) SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgResp, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.SendMsg(ctx, in, opts...)
}

// 获取消息历史
func (m *defaultMsg) GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error) {
	client := msg.NewMsgClient(m.cli.Conn())
	return client.GetHistory(ctx, in, opts...)
}
