// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	group "easy-chat/apps/group/api/internal/handler/group"
	"easy-chat/apps/group/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: group.CreateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dismiss",
				Handler: group.DismissGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: group.GetGroupInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/info",
				Handler: group.UpdateGroupInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/info/batch",
				Handler: group.GetGroupsInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/join",
				Handler: group.JoinGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/leave",
				Handler: group.LeaveGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/member/admin",
				Handler: group.SetAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/member/check",
				Handler: group.IsInGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/member/kick",
				Handler: group.KickMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/member/mute",
				Handler: group.MuteMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/members",
				Handler: group.GetGroupMembersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/owner/transfer",
				Handler: group.TransferOwnerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/groups",
				Handler: group.GetUserGroupsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/group"),
	)
}
