// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	msgFieldNames          = builder.RawFieldNames(&Msg{})
	msgRows                = strings.Join(msgFieldNames, ",")
	msgRowsExpectAutoSet   = strings.Join(stringx.Remove(msgFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	msgRowsWithPlaceHolder = strings.Join(stringx.Remove(msgFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMsgIdPrefix    = "cache:msg:id:"
	cacheMsgMsgIdPrefix = "cache:msg:msgId:"
)

type (
	msgModel interface {
		Insert(ctx context.Context, data *Msg) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Msg, error)
		FindOneByMsgId(ctx context.Context, msgId string) (*Msg, error)
		Update(ctx context.Context, data *Msg) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMsgModel struct {
		sqlc.CachedConn
		table string
	}

	Msg struct {
		Id         uint64 `db:"id"`
		MsgId      string `db:"msg_id"`      // 业务ID
		FromUid    int64  `db:"from_uid"`    // 发送者ID
		ToUid      int64  `db:"to_uid"`      // 接收者ID
		GroupId    int64  `db:"group_id"`    // 群ID
		Type       int64  `db:"type"`        // 消息类型
		Content    string `db:"content"`     // 消息内容
		CreateTime int64  `db:"create_time"` // 发送时间(ms)
	}
)

func newMsgModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMsgModel {
	return &defaultMsgModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`msg`",
	}
}

func (m *defaultMsgModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	msgIdKey := fmt.Sprintf("%s%v", cacheMsgIdPrefix, id)
	msgMsgIdKey := fmt.Sprintf("%s%v", cacheMsgMsgIdPrefix, data.MsgId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, msgIdKey, msgMsgIdKey)
	return err
}

func (m *defaultMsgModel) FindOne(ctx context.Context, id uint64) (*Msg, error) {
	msgIdKey := fmt.Sprintf("%s%v", cacheMsgIdPrefix, id)
	var resp Msg
	err := m.QueryRowCtx(ctx, &resp, msgIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", msgRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMsgModel) FindOneByMsgId(ctx context.Context, msgId string) (*Msg, error) {
	msgMsgIdKey := fmt.Sprintf("%s%v", cacheMsgMsgIdPrefix, msgId)
	var resp Msg
	err := m.QueryRowIndexCtx(ctx, &resp, msgMsgIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `msg_id` = ? limit 1", msgRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, msgId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMsgModel) Insert(ctx context.Context, data *Msg) (sql.Result, error) {
	msgIdKey := fmt.Sprintf("%s%v", cacheMsgIdPrefix, data.Id)
	msgMsgIdKey := fmt.Sprintf("%s%v", cacheMsgMsgIdPrefix, data.MsgId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, msgRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MsgId, data.FromUid, data.ToUid, data.GroupId, data.Type, data.Content)
	}, msgIdKey, msgMsgIdKey)
	return ret, err
}

func (m *defaultMsgModel) Update(ctx context.Context, newData *Msg) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	msgIdKey := fmt.Sprintf("%s%v", cacheMsgIdPrefix, data.Id)
	msgMsgIdKey := fmt.Sprintf("%s%v", cacheMsgMsgIdPrefix, data.MsgId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, msgRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MsgId, newData.FromUid, newData.ToUid, newData.GroupId, newData.Type, newData.Content, newData.Id)
	}, msgIdKey, msgMsgIdKey)
	return err
}

func (m *defaultMsgModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMsgIdPrefix, primary)
}

func (m *defaultMsgModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", msgRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMsgModel) tableName() string {
	return m.table
}
