// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息详情 (对应你的 BroadcastMsg 结构，用于历史记录返回)
type MsgData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                   // 对应 MsgId
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 对应 FromUserId
	ToUserId      int64                  `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`       // 单聊时使用
	GroupId       int64                  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`            // 群聊时使用 ← 新增
	Type          int64                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`                                 // 对应 Type: 1-单聊, 2-群聊
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                            // 对应 Content
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // 对应 Timestamp
	Seq           int64                  `protobuf:"varint,8,opt,name=seq,proto3" json:"seq,omitempty"`                                   // 对应 Seq
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgData) Reset() {
	*x = MsgData{}
	mi := &file_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgData) ProtoMessage() {}

func (x *MsgData) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgData.ProtoReflect.Descriptor instead.
func (*MsgData) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MsgData) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MsgData) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *MsgData) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *MsgData) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MsgData) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MsgData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MsgData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MsgData) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 1. 发送消息请求 (Gateway -> Msg RPC)
type SendMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 发送人 (从Token解析)
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`       // 接收人
	GroupId       int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`            // 群聊时使用 ← 新增
	Type          int64                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                                 // 1-单聊, 2-群聊
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                            // 内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	mi := &file_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *SendMsgReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *SendMsgReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *SendMsgReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SendMsgReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SendMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 发送消息响应
type SendMsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // 服务端生成的唯一ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`     // 服务端生成的发送时间
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`                 // 会话内消息序列号 ← 新增
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgResp) Reset() {
	*x = SendMsgResp{}
	mi := &file_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgResp) ProtoMessage() {}

func (x *SendMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgResp.ProtoReflect.Descriptor instead.
func (*SendMsgResp) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *SendMsgResp) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendMsgResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SendMsgResp) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 2. 获取历史消息请求 (API -> Msg RPC)
type GetHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 当前查看的用户
	PeerId        int64                  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`          // 对方ID (好友ID 或 群ID)
	Type          int64                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                            // 1-单聊, 2-群聊
	AnchorSeq     int64                  `protobuf:"varint,4,opt,name=anchor_seq,json=anchorSeq,proto3" json:"anchor_seq,omitempty"` // 锚点seq（0表示首次加载，拉取最新消息）
	Direction     int32                  `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`                  // 查询方向: 0-向前(查历史), 1-向后(查新消息)
	Limit         int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`                          // 单次返回条数限制（默认20，最大100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryReq) Reset() {
	*x = GetHistoryReq{}
	mi := &file_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReq) ProtoMessage() {}

func (x *GetHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHistoryReq) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetHistoryReq) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *GetHistoryReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetHistoryReq) GetAnchorSeq() int64 {
	if x != nil {
		return x.AnchorSeq
	}
	return 0
}

func (x *GetHistoryReq) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *GetHistoryReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取历史消息响应
type GetHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MsgData             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`                       // 消息列表
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // 是否还有更多消息
	NextSeq       int64                  `protobuf:"varint,3,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"` // 下次请求的anchor_seq（用于分页）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResp) Reset() {
	*x = GetHistoryResp{}
	mi := &file_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResp) ProtoMessage() {}

func (x *GetHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResp.ProtoReflect.Descriptor instead.
func (*GetHistoryResp) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResp) GetList() []*MsgData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetHistoryResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetHistoryResp) GetNextSeq() int64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

var File_msg_proto protoreflect.FileDescriptor

const file_msg_proto_rawDesc = "" +
	"\n" +
	"\tmsg.proto\x12\x03msg\"\xd9\x01\n" +
	"\aMsgData\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x03R\btoUserId\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x03R\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03seq\x18\b \x01(\x03R\x03seq\"\x95\x01\n" +
	"\n" +
	"SendMsgReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"T\n" +
	"\vSendMsgResp\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"\xa8\x01\n" +
	"\rGetHistoryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x03R\x06peerId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x03R\x04type\x12\x1d\n" +
	"\n" +
	"anchor_seq\x18\x04 \x01(\x03R\tanchorSeq\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x05R\tdirection\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\"h\n" +
	"\x0eGetHistoryResp\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.msg.MsgDataR\x04list\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x19\n" +
	"\bnext_seq\x18\x03 \x01(\x03R\anextSeq2j\n" +
	"\x03Msg\x12,\n" +
	"\aSendMsg\x12\x0f.msg.SendMsgReq\x1a\x10.msg.SendMsgResp\x125\n" +
	"\n" +
	"GetHistory\x12\x12.msg.GetHistoryReq\x1a\x13.msg.GetHistoryRespB\aZ\x05./msgb\x06proto3"

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData []byte
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)))
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_msg_proto_goTypes = []any{
	(*MsgData)(nil),        // 0: msg.MsgData
	(*SendMsgReq)(nil),     // 1: msg.SendMsgReq
	(*SendMsgResp)(nil),    // 2: msg.SendMsgResp
	(*GetHistoryReq)(nil),  // 3: msg.GetHistoryReq
	(*GetHistoryResp)(nil), // 4: msg.GetHistoryResp
}
var file_msg_proto_depIdxs = []int32{
	0, // 0: msg.GetHistoryResp.list:type_name -> msg.MsgData
	1, // 1: msg.Msg.SendMsg:input_type -> msg.SendMsgReq
	3, // 2: msg.Msg.GetHistory:input_type -> msg.GetHistoryReq
	2, // 3: msg.Msg.SendMsg:output_type -> msg.SendMsgResp
	4, // 4: msg.Msg.GetHistory:output_type -> msg.GetHistoryResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
