// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: apps/msg/rpc/msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息详情 (对应你的 BroadcastMsg 结构，用于历史记录返回)
type MsgData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                   // 对应 MsgId
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 对应 FromUserId
	ToUserId      int64                  `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`       // 对应 ToUserId (如果是群聊，这里存群ID)
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                                 // 对应 Type: 1-单聊, 2-群聊
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                            // 对应 Content
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // 对应 Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgData) Reset() {
	*x = MsgData{}
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgData) ProtoMessage() {}

func (x *MsgData) ProtoReflect() protoreflect.Message {
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgData.ProtoReflect.Descriptor instead.
func (*MsgData) Descriptor() ([]byte, []int) {
	return file_apps_msg_rpc_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MsgData) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MsgData) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *MsgData) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *MsgData) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MsgData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MsgData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 1. 发送消息请求 (Gateway -> Msg RPC)
type SendMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 发送人 (从Token解析)
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`       // 接收人/群ID
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                                 // 1-单聊, 2-群聊
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                            // 内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_apps_msg_rpc_msg_proto_rawDescGZIP(), []int{1}
}

func (x *SendMsgReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *SendMsgReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *SendMsgReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SendMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 发送消息响应
type SendMsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // 服务端生成的唯一ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`     // 服务端生成的发送时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgResp) Reset() {
	*x = SendMsgResp{}
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgResp) ProtoMessage() {}

func (x *SendMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgResp.ProtoReflect.Descriptor instead.
func (*SendMsgResp) Descriptor() ([]byte, []int) {
	return file_apps_msg_rpc_msg_proto_rawDescGZIP(), []int{2}
}

func (x *SendMsgResp) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendMsgResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 2. 获取历史消息请求 (API -> Msg RPC)
type GetHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 当前查看的用户
	PeerId        int64                  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`       // 对方ID (好友ID 或 群ID)
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                         // 1-单聊, 2-群聊
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int64                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryReq) Reset() {
	*x = GetHistoryReq{}
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReq) ProtoMessage() {}

func (x *GetHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHistoryReq) Descriptor() ([]byte, []int) {
	return file_apps_msg_rpc_msg_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetHistoryReq) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *GetHistoryReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetHistoryReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHistoryReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取历史消息响应
type GetHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MsgData             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 消息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResp) Reset() {
	*x = GetHistoryResp{}
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResp) ProtoMessage() {}

func (x *GetHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_msg_rpc_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResp.ProtoReflect.Descriptor instead.
func (*GetHistoryResp) Descriptor() ([]byte, []int) {
	return file_apps_msg_rpc_msg_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResp) GetList() []*MsgData {
	if x != nil {
		return x.List
	}
	return nil
}

var File_apps_msg_rpc_msg_proto protoreflect.FileDescriptor

const file_apps_msg_rpc_msg_proto_rawDesc = "" +
	"\n" +
	"\x16apps/msg/rpc/msg.proto\x12\x03msg\"\xac\x01\n" +
	"\aMsgData\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x03R\btoUserId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"z\n" +
	"\n" +
	"SendMsgReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"B\n" +
	"\vSendMsgResp\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x86\x01\n" +
	"\rGetHistoryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x03R\x06peerId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x03R\bpageSize\"2\n" +
	"\x0eGetHistoryResp\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.msg.MsgDataR\x04list2j\n" +
	"\x03Msg\x12,\n" +
	"\aSendMsg\x12\x0f.msg.SendMsgReq\x1a\x10.msg.SendMsgResp\x125\n" +
	"\n" +
	"GetHistory\x12\x12.msg.GetHistoryReq\x1a\x13.msg.GetHistoryRespB\aZ\x05./msgb\x06proto3"

var (
	file_apps_msg_rpc_msg_proto_rawDescOnce sync.Once
	file_apps_msg_rpc_msg_proto_rawDescData []byte
)

func file_apps_msg_rpc_msg_proto_rawDescGZIP() []byte {
	file_apps_msg_rpc_msg_proto_rawDescOnce.Do(func() {
		file_apps_msg_rpc_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_msg_rpc_msg_proto_rawDesc), len(file_apps_msg_rpc_msg_proto_rawDesc)))
	})
	return file_apps_msg_rpc_msg_proto_rawDescData
}

var file_apps_msg_rpc_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apps_msg_rpc_msg_proto_goTypes = []any{
	(*MsgData)(nil),        // 0: msg.MsgData
	(*SendMsgReq)(nil),     // 1: msg.SendMsgReq
	(*SendMsgResp)(nil),    // 2: msg.SendMsgResp
	(*GetHistoryReq)(nil),  // 3: msg.GetHistoryReq
	(*GetHistoryResp)(nil), // 4: msg.GetHistoryResp
}
var file_apps_msg_rpc_msg_proto_depIdxs = []int32{
	0, // 0: msg.GetHistoryResp.list:type_name -> msg.MsgData
	1, // 1: msg.Msg.SendMsg:input_type -> msg.SendMsgReq
	3, // 2: msg.Msg.GetHistory:input_type -> msg.GetHistoryReq
	2, // 3: msg.Msg.SendMsg:output_type -> msg.SendMsgResp
	4, // 4: msg.Msg.GetHistory:output_type -> msg.GetHistoryResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_msg_rpc_msg_proto_init() }
func file_apps_msg_rpc_msg_proto_init() {
	if File_apps_msg_rpc_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_msg_rpc_msg_proto_rawDesc), len(file_apps_msg_rpc_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_msg_rpc_msg_proto_goTypes,
		DependencyIndexes: file_apps_msg_rpc_msg_proto_depIdxs,
		MessageInfos:      file_apps_msg_rpc_msg_proto_msgTypes,
	}.Build()
	File_apps_msg_rpc_msg_proto = out.File
	file_apps_msg_rpc_msg_proto_goTypes = nil
	file_apps_msg_rpc_msg_proto_depIdxs = nil
}
