// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: msg.proto

package server

import (
	"context"

	"easy-chat/apps/msg/rpc/internal/logic"
	"easy-chat/apps/msg/rpc/internal/svc"
	"easy-chat/apps/msg/rpc/msg"
)

type MsgServer struct {
	svcCtx *svc.ServiceContext
	msg.UnimplementedMsgServer
}

func NewMsgServer(svcCtx *svc.ServiceContext) *MsgServer {
	return &MsgServer{
		svcCtx: svcCtx,
	}
}

// 发送消息：处理存储、生成ID、广播
func (s *MsgServer) SendMsg(ctx context.Context, in *msg.SendMsgReq) (*msg.SendMsgResp, error) {
	l := logic.NewSendMsgLogic(ctx, s.svcCtx)
	return l.SendMsg(in)
}

// 获取消息历史
func (s *MsgServer) GetHistory(ctx context.Context, in *msg.GetHistoryReq) (*msg.GetHistoryResp, error) {
	l := logic.NewGetHistoryLogic(ctx, s.svcCtx)
	return l.GetHistory(in)
}
