// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: apps/user/rpc/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// model
type UserEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // 用户id
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 用户头像
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"` // 昵称
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`       // 手机号码
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`    // 是否锁住
	Sex           int32                  `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEntity) Reset() {
	*x = UserEntity{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEntity) ProtoMessage() {}

func (x *UserEntity) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEntity.ProtoReflect.Descriptor instead.
func (*UserEntity) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserEntity) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserEntity) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserEntity) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserEntity) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserEntity) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

// req 与 respo
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Expire        int64                  `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex           int32                  `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RegisterReq) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Expire        int64                  `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserEntity            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoResp) GetUser() *UserEntity {
	if x != nil {
		return x.User
	}
	return nil
}

type FindUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"` // 昵称
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`       // 手机号
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`           // 用户ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserReq) Reset() {
	*x = FindUserReq{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserReq) ProtoMessage() {}

func (x *FindUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserReq.ProtoReflect.Descriptor instead.
func (*FindUserReq) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{9}
}

func (x *FindUserReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FindUserReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *FindUserReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*UserEntity          `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserResp) Reset() {
	*x = FindUserResp{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserResp) ProtoMessage() {}

func (x *FindUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserResp.ProtoReflect.Descriptor instead.
func (*FindUserResp) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{10}
}

func (x *FindUserResp) GetUser() []*UserEntity {
	if x != nil {
		return x.User
	}
	return nil
}

var File_apps_user_rpc_user_proto protoreflect.FileDescriptor

const file_apps_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x18apps/user/rpc/user.proto\x12\x04user\"\x90\x01\n" +
	"\n" +
	"UserEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x10\n" +
	"\x03sex\x18\x06 \x01(\x05R\x03sex\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"<\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"9\n" +
	"\tLoginResp\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\x03R\x06expire\"\x85\x01\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\x05R\x03sex\"<\n" +
	"\fRegisterResp\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\x03R\x06expire\" \n" +
	"\x0eGetUserInfoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x0fGetUserInfoResp\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.user.UserEntityR\x04user\"Q\n" +
	"\vFindUserReq\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\"4\n" +
	"\fFindUserResp\x12$\n" +
	"\x04user\x18\x01 \x03(\v2\x10.user.UserEntityR\x04user2\xf9\x01\n" +
	"\x04User\x12%\n" +
	"\x04Ping\x12\r.user.Request\x1a\x0e.user.Response\x12(\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x121\n" +
	"\bRegister\x12\x11.user.RegisterReq\x1a\x12.user.RegisterResp\x12:\n" +
	"\vGetUserInfo\x12\x14.user.GetUserInfoReq\x1a\x15.user.GetUserInfoResp\x121\n" +
	"\bFindUser\x12\x11.user.FindUserReq\x1a\x12.user.FindUserRespB\bZ\x06./userb\x06proto3"

var (
	file_apps_user_rpc_user_proto_rawDescOnce sync.Once
	file_apps_user_rpc_user_proto_rawDescData []byte
)

func file_apps_user_rpc_user_proto_rawDescGZIP() []byte {
	file_apps_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_apps_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_user_rpc_user_proto_rawDesc), len(file_apps_user_rpc_user_proto_rawDesc)))
	})
	return file_apps_user_rpc_user_proto_rawDescData
}

var file_apps_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apps_user_rpc_user_proto_goTypes = []any{
	(*UserEntity)(nil),      // 0: user.UserEntity
	(*Request)(nil),         // 1: user.Request
	(*Response)(nil),        // 2: user.Response
	(*LoginReq)(nil),        // 3: user.LoginReq
	(*LoginResp)(nil),       // 4: user.LoginResp
	(*RegisterReq)(nil),     // 5: user.RegisterReq
	(*RegisterResp)(nil),    // 6: user.RegisterResp
	(*GetUserInfoReq)(nil),  // 7: user.GetUserInfoReq
	(*GetUserInfoResp)(nil), // 8: user.GetUserInfoResp
	(*FindUserReq)(nil),     // 9: user.FindUserReq
	(*FindUserResp)(nil),    // 10: user.FindUserResp
}
var file_apps_user_rpc_user_proto_depIdxs = []int32{
	0,  // 0: user.GetUserInfoResp.user:type_name -> user.UserEntity
	0,  // 1: user.FindUserResp.user:type_name -> user.UserEntity
	1,  // 2: user.User.Ping:input_type -> user.Request
	3,  // 3: user.User.Login:input_type -> user.LoginReq
	5,  // 4: user.User.Register:input_type -> user.RegisterReq
	7,  // 5: user.User.GetUserInfo:input_type -> user.GetUserInfoReq
	9,  // 6: user.User.FindUser:input_type -> user.FindUserReq
	2,  // 7: user.User.Ping:output_type -> user.Response
	4,  // 8: user.User.Login:output_type -> user.LoginResp
	6,  // 9: user.User.Register:output_type -> user.RegisterResp
	8,  // 10: user.User.GetUserInfo:output_type -> user.GetUserInfoResp
	10, // 11: user.User.FindUser:output_type -> user.FindUserResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_apps_user_rpc_user_proto_init() }
func file_apps_user_rpc_user_proto_init() {
	if File_apps_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_user_rpc_user_proto_rawDesc), len(file_apps_user_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_apps_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_apps_user_rpc_user_proto_msgTypes,
	}.Build()
	File_apps_user_rpc_user_proto = out.File
	file_apps_user_rpc_user_proto_goTypes = nil
	file_apps_user_rpc_user_proto_depIdxs = nil
}
